# Generated by Django 5.0.3 on 2024-03-16 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id_gender', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id_news', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nhập tên Tin Tức ...', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='artist',
            fields=[
                ('id_artist', models.AutoField(primary_key=True, serialize=False)),
                ('is_sub', models.BooleanField(default=False)),
                ('name', models.CharField(default='nameArtist', max_length=200)),
                ('slug', models.SlugField(default='slugArtist', max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('sub_artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_artists', to='mymusic_home.artist')),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id_genre', models.AutoField(primary_key=True, serialize=False)),
                ('is_sub', models.BooleanField(default=False)),
                ('name', models.CharField(default='nameGenre', max_length=200)),
                ('slug', models.SlugField(default='slugGenre', max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('sub_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_genres', to='mymusic_home.genre')),
            ],
        ),
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id_playlist', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(help_text='Nhập vào tên danh sách phát...', max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id_song', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nhập vào tên bài hát ...', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('fileMp3', models.FileField(blank=True, null=True, upload_to='')),
                ('artist', models.ManyToManyField(related_name='songArtist', to='mymusic_home.artist')),
                ('genre', models.ManyToManyField(related_name='songGenre', to='mymusic_home.genre')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='playlist_detail',
            fields=[
                ('id_playlist_detail', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymusic_home.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymusic_home.song')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(help_text='Hãy nhập tên người dùng', max_length=200, null=True)),
                ('birth', models.DateField(null=True)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('id_gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mymusic_home.gender')),
            ],
        ),
    ]
