# Generated by Django 5.0.3 on 2024-03-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymusic_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
