# Generated by Django 5.0.3 on 2024-03-19 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymusic_home', '0002_artist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 2, 11, 5, 279940)),
        ),
    ]
